version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000" # Expose Next.js port (for development or direct access)
    environment:
      NODE_ENV: production
    networks:
      - gedomed-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose Nginx port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nextjs:/var/www/nextjs
    depends_on:
      - nextjs
    networks:
      - gedomed-network

networks:
  gedomed-network:
    driver: bridge